#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Boston University Data Services

# Short bio or description (displayed in the header)
description: Data Services at Boston University 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: #https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: data@bu.edu
  github: bulib
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: #jekyllrb
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.bu.edu/data

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"


# For BU web development site: 
baseurl: "/dev/data"

# For GitHub
#baseurl: "/dataWebsite"

# For production site - bu.edu/data
# baseurl: "/data"


#
# !! You don't need to change any of the configuration flags below !!
#

highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: compressed  # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

defaults: 
  - 
    scope: 
      path: ""
      type: "pages"
    values: 
      layout: "page"   
  - 
    scope: 
      path: ""
      type: "posts"
    values: 
      layout: "post"

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - /talks/*/slides.md


